version: "3.4"
services:
  matomo:
    image: matomo
    networks:
      - webgateway
      - db-net
    volumes:
      - conf-vol:/var/www/html/config
    deploy:
      labels:
        traefik.docker.network: webgateway
        traefik.frontend.rule: Host:analytics.ubports.com
        traefik.port: 80
  db:
    image: mariadb
    networks:
      - db-net
    deploy:
       replicas: 1
    volumes:
       - db-vol:/var/lib/mysql
    secrets:
       - matomo_db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/matomo_db_password
      MYSQL_DATABASE: matomo

networks:
  db-net:
  webgateway:
    driver: overlay
    external: true

volumes:
  db-vol:
  conf-vol:

secrets:
   matomo_db_password:
     external: true
