version: '3.4'

services:
  traefik:
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/opt/conf/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=infra@ubports.com"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.watch"
      - "--debug"
      - "--insecureSkipVerify=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - conf-volume:/opt/conf
    networks:
      - webgateway
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: webgateway
        traefik.frontend.rule: Host:proxy.infra.ubports.com
        traefik.port: 8080
networks:
  webgateway:
    driver: overlay
    external: true
volumes:
  conf-volume:
