version: "3.4"
services:
  redmine:
    image: redmine
    networks:
      - webgateway
      - db-net
    secrets:
      - redmine_db_password 
    volumes:
      - redmine-volume:/usr/src/redmine/files
    deploy:  
      labels:
        - "traefik.docker.network: webgateway"
        - "traefik.frontend.rule=Host:redmine2.ubports.com"
        - "traefik.port=3000"
    environment:
      REDMINE_DB_MYSQL: db     
      REDMINE_DB_PASSWORD_FILE: /run/secrets/redmine_db_password
  db:
    image: mariadb
    secrets:
      - redmine_db_password
    networks:
      - db-net
    deploy:
       replicas: 1
    volumes:
       - db-volume:/var/lib/mysql
    environment:  
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/redmine_db_password
      MYSQL_DATABASE: redmine

networks:  
  db-net:
  webgateway:    
    driver: overlay
    external: true 

volumes:    
  db-volume:
  redmine-volume:

secrets:
   redmine_db_password:
     external: true
